name: comics_app
description: Comics Collection

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+1

environment:
  sdk: ">=2.9.2 <3.0.0"
  flutter: ^1.20.3

dependencies:
  flutter:
    sdk: flutter

  animations: ^1.1.2
  cached_network_image: ^2.3.2+1
  dio: ^3.0.10
  dio_flutter_transformer: ^3.0.2
  dio_http_cache: ^0.2.8
  retrofit: ^1.3.4
  flutter_mobx: ^1.1.0+2
  flutter_svg: ^0.19.0
  get_version: ^0.2.2
  intl: ^0.16.1
  json_annotation: ^3.0.1
  mobx: ^1.2.1+2
  provider: ^4.3.2+2
  url_launcher: ^5.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.1
  json_serializable: ^3.4.1
  mobx_codegen: ^1.1.0+1
  retrofit_generator: ^1.3.7+6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/HelveticaNeue-Light.ttf
          weight: 200
        - asset: assets/fonts/HelveticaNeue.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue-Medium.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue-Bold.ttf
          weight: 700
    - family: Helvetica Neue Condensed
      fonts:
        - asset: assets/fonts/HelveticaNeue-CondensedBold.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue-CondensedBlack.ttf
          weight: 900
