name: comics_app
description: Comics Collection

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_mobx: ^1.0.1
  flutter_svg: ^0.17.2
  json_annotation: ^3.0.1
  mobx: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.4
  json_serializable: ^3.2.5
  mobx_codegen: ^1.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/icons/

  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/HelveticaNeue-Light.ttf
          weight: 200
        - asset: assets/fonts/HelveticaNeue.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue-Medium.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue-Bold.ttf
          weight: 700
    - family: Helvetica Neue Condensed
      fonts:
        - asset: assets/fonts/HelveticaNeue-CondensedBold.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue-CondensedBlack.ttf
          weight: 900
